{% set name = "django-filer" %}
{% set version = "3.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ea7c137431c0376222bfca99f61d2878a55c3e26ad11e4a800009e82ffb51091

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - django-polymorphic !=4.9.0
    - python >={{ python_min }}
    - django >=3.2
    - django_polymorphic
    - easy-thumbnails
    # https://github.com/django-cms/django-filer/blob/master/setup.py#L10C1-L10C28 
    # pip requirement is easy-thumbnails[svg] requiring svglib and reportlab
    # https://github.com/SmileyChris/easy-thumbnails/blob/master/setup.py#L39
    - svglib >=1.5.1,<1.6.dev0
    - reportlab

test:
  imports:
    - filer
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/divio/django-filer
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'File and Image Management Application for django'
  description: A file management application for django that makes handling of files and images a breeze.
  doc_url: https://django-filer.readthedocs.io/
  dev_url: https://github.com/divio/django-filer

extra:
  recipe-maintainers:
    - darynwhite
    - cshaley
    - sannykr
    - rxm7706
