{% set name = "django-filer" %}
{% set version = "3.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e59ab99212dfde1a470c0b3658fa50f24fc0f81465f18390630e991b253611cc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - django >=3.2,<5.1
    - django_polymorphic
    - easy-thumbnails

test:
  imports:
    - filer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/divio/django-filer
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'File and Image Management Application for django'
  description: A file management application for django that makes handling of files and images a breeze.
  doc_url: https://django-filer.readthedocs.io/
  dev_url: https://github.com/divio/django-filer

extra:
  recipe-maintainers:
    - darynwhite
    - cshaley
    - sannykr
    - rxm7706
