{% set name = "django-filer" %}
{% set version = "3.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 397c0b0f313371cc9e0cd92b3f1b0023b8dd213d7ebd038d6e289437df027bd0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - django >=3.2
    - django_polymorphic
    - easy-thumbnails
# https://github.com/django-cms/django-filer/blob/master/setup.py#L10C1-L10C28 
# pip requirement is easy-thumbnails[svg] requiring svglib and reportlab
# https://github.com/SmileyChris/easy-thumbnails/blob/master/setup.py#L39
    - svglib
    - reportlab

test:
  imports:
    - filer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/divio/django-filer
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'File and Image Management Application for django'
  description: A file management application for django that makes handling of files and images a breeze.
  doc_url: https://django-filer.readthedocs.io/
  dev_url: https://github.com/divio/django-filer

extra:
  recipe-maintainers:
    - darynwhite
    - cshaley
    - sannykr
    - rxm7706
